global:
  scrape_interval: 10s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'fastapi_app'  # Название задачи для сбора метрик с FastAPI приложения
    static_configs:
      - targets: ['fastapi_app:9999']  # Цель - FastAPI приложение, которое запущено на порте 8000
    metrics_path: /metrics
    scheme: http

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Сбор метрик с самого Prometheus
