"""Update datetime to use timezone

Revision ID: 6aea5b310b06
Revises: 476aa5bf8377
Create Date: 2024-10-07 16:21:04.219662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aea5b310b06'
down_revision: Union[str, None] = '476aa5bf8377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
