"""Change registered_at to TIMESTAMP WITH TIME ZONE

Revision ID: feb857e302bd
Revises: 6aea5b310b06
Create Date: 2024-10-08 20:01:24.385776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb857e302bd'
down_revision: Union[str, None] = '6aea5b310b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
